<font color='green'>

# Matrislerde Çarpım İşlemleri

###   Bu notta numpy kütüphanesi ile _skaler ve vektörel_ çarpım gibi matematiksel işlemlerin üzerinde duracağız. Matris dediğimiz için sadece iki veya daha fazla boyuttaki array'lerle ilgileneceğiz. Ya da bir diğer deyişle tek boyutlu array'ler bu konu başlığı altında bulunmayacaktır.

In [3]:
import numpy as np

In [4]:
a= np.array([[(1,2),(3,4)]])
b= np.array([[(5,6),(7,8)]])

Önce bu iki boyutlu 'a' ve 'b' array'lerimizi görelim:

In [5]:
a

array([[[1, 2],
        [3, 4]]])

In [6]:
b

array([[[5, 6],
        [7, 8]]])

#### *  İki vektörün çarpımı :

bu iki vektörün çarpımını c'ye eşitleyelim ve c array'ini ekranda bastıralım.

In [8]:
c=np.dot(a,b)
c

array([[[[19, 22]],

        [[43, 50]]]])

aynı işlemi farklı bir syntax yapısı ile yapalım:

In [9]:
c=(a.dot(b))
c

array([[[[19, 22]],

        [[43, 50]]]])

**HATIRLATMA:** Lineer cebir dersinde gördüğümüz iki matrisin çarpım kuralı :

![](matas.png)

Bizim tanımladığımız 'a' ve 'b' array'lerine göre işlemleri düzenlersek:

![](cozum.jpeg)

> Yazının kötülüğünden dolayı özür dilerim :D

Görüldüğü üzere sonuçlar aynı çıktı.

#### * İki boyutlu matrisin skaler çarpımı:

In [10]:
v=np.array([[(1,2),(3,4)]])
v

array([[[1, 2],
        [3, 4]]])

In [12]:
np.multiply(v,2)

array([[[2, 4],
        [6, 8]]])

## Numpy kütüphanesi hakkında topladığım notların sonuna geldim. Umarım faydalı olmuştur. Yeni bilgiler edindikçe ve fırsat buldukça güncellemeler yapmaya çalışacağım. Eşli eden herkese teşekkürler :)